### ISSUE TITLE
Kdaj gremo tole kej stestirat?

### ISSUE THREAD

**Issue by zigapk** [Sourcegasm/RiftVision#2]

**Comment by PyloDEV** [comment]
Ja lohk enkrat sam pomojem mormo napisat na FE če lahko dobimo quada ker ta od OpenWeeka in iz FE.

**Comment by zigapk** [comment]
Kdo bo?

**Comment by zigapk** [comment]
Evo vid je assigned

**Comment by PyloDEV** [comment]
Hahah Vid najboljš da napišeš Matevžu da nam da oculus pa en dron pa baterije + polnilnik: matevz.bosnak@fe.uni-lj.si

**Comment by zigapk** [comment]
a si ze prasu vid?
